Hu 04 backend
ProjektAlmanac/Amoxtli pull request #16
Opened 2023-10-05 23:36 UTC by laloCastro22

2023-10-05 23:37 UTC, laloCastro22 commented
Hu-04

2023-10-06 00:33 UTC, AntarEspadas requested changes

2023-10-06 00:33 UTC, AntarEspadas commented on backend/src/main/java/io/github/projektalmanac/amoxtli/backend/mapper/UserMapper.java
> +    @Mapping(source = "id", target = "id")
```suggestion
```
Este mapping es redundante

2023-10-06 00:33 UTC, AntarEspadas commented on backend/src/main/java/io/github/projektalmanac/amoxtli/backend/mapper/UserMapper.java
> +    @Mapping(source = "correoVerificado", target = "verificationCode")
`correoVerificado` indica si el correo ha sido verificado o no, `verificationCode` es el código de verificación. No son el mismo campo, ni siquiera son del mismo tipo (uno es un String y el otro es un booleano), por lo que no se debería mapear uno al otro

2023-10-06 00:33 UTC, AntarEspadas commented on backend/src/main/java/io/github/projektalmanac/amoxtli/backend/mapper/UserMapper.java
> +    @Mapping(source = "id", target = "id")
```suggestion
```
Mapeo redundante

2023-10-06 00:33 UTC, AntarEspadas commented on backend/src/main/java/io/github/projektalmanac/amoxtli/backend/mapper/UserMapper.java
> +    @Mapping(source = "verifiedEmail", target = "correoVerificado")
Lo mismo que con el anterior

2023-10-06 00:33 UTC, AntarEspadas commented on backend/src/main/java/io/github/projektalmanac/amoxtli/backend/repository/UserRepository.java
> +    public User getUserById(Integer id);
No el repositorio ya trae un método `getById` sin necesidad de que declares uno manualmente?

2023-10-06 00:33 UTC, AntarEspadas commented on backend/src/main/java/io/github/projektalmanac/amoxtli/backend/service/UserService.java
> +    @Autowired
```suggestion
    private UserRepository userRepository;

    @Slf4j
    @Autowired
```

Tenemos lombock, úsalo.

2023-10-06 00:33 UTC, AntarEspadas commented on backend/src/main/java/io/github/projektalmanac/amoxtli/backend/service/UserService.java
> +        LOGGER.info(">>PerfilUsuarioDto {}", id);
```suggestion
        log.info(">>PerfilUsuarioDto {}", id);
```

Si usas la anotación `@Slf4j` de lombock, usa `log` en lugar de `LOGGER`

2023-10-06 00:33 UTC, AntarEspadas commented on backend/src/main/java/io/github/projektalmanac/amoxtli/backend/service/UserService.java
> +            throw new IllegalArgumentException("Error, el mapeo no fue exitoso");
Hasta donde tengo entendido, los mappers de MapStruct no pueden regresar `null`. Viste en algún lugar que fuera así?

2023-10-06 00:33 UTC, AntarEspadas commented on backend/src/main/java/io/github/projektalmanac/amoxtli/backend/service/UserService.java
> +        }
Recuerda que los DTOs que manda el frontend al backend no tienen ID. Es muy probable que este ID siempre venga con 0 o `null`

2023-10-06 00:33 UTC, AntarEspadas commented on backend/src/main/java/io/github/projektalmanac/amoxtli/backend/service/UserService.java
> +        user = this.userRepository.save(user);
No tienes que hacer todo esto. Nada te impiede guardad `user` en el repositorio. Solo asegúrate de ponerle manualmente el ID que no trae el DTO

2023-10-06 00:33 UTC, AntarEspadas commented on backend/src/main/java/io/github/projektalmanac/amoxtli/backend/service/UserService.java
> +        }
Si la especificación de openapi está mal, avisa para que se cambie, no hagas cosas raras en tu código

2023-10-06 00:33 UTC, AntarEspadas commented on backend/src/main/java/io/github/projektalmanac/amoxtli/backend/service/UserService.java
> +        }
Hasta donde sé, el método `save` no puede regresar null

2023-10-06 00:33 UTC, AntarEspadas commented on backend/src/test/java/io/github/projektalmanac/amoxtli/backend/serviceTest/UserServiceTest.java
> +        //Caso 2. El usuario existe pero su correo no esta autenticado
```suggestion
        //Caso 2. El usuario existe pero su correo no esta verificado
```

2023-10-06 00:33 UTC, AntarEspadas commented on backend/src/test/java/io/github/projektalmanac/amoxtli/backend/serviceTest/UserServiceTest.java
> +        Assertions.assertEquals(false,result,"El usuario no esta autenticado");
Aquí no estás probando el método `getUsuario`, estás probando la precondición que tú mismo pusiste en el @BeforeEach

2023-10-06 00:33 UTC, AntarEspadas commented on backend/src/test/java/io/github/projektalmanac/amoxtli/backend/serviceTest/UserServiceTest.java
> +        Assertions.assertNotNull(perfilUsuarioDto,"EL mapeo fue exitoso");
Esta línea de código va a mostrar el mensaje `EL mapeo fue exitoso` si el método regresa `null`. Es eso lo que quieres?

2023-10-06 00:33 UTC, AntarEspadas commented on backend/src/test/java/io/github/projektalmanac/amoxtli/backend/serviceTest/UserServiceTest.java
> +        Assertions.assertEquals(false,result,"El usuario no esta autenticado");
Igual que antes, nada más estás probando tu precondición

2023-10-06 00:33 UTC, AntarEspadas commented on backend/src/test/java/io/github/projektalmanac/amoxtli/backend/serviceTest/UserServiceTest.java
> +        userService.actualizaUsuario(2,perfilUsuarioDtoCambio);
No estás probando nada

2023-10-06 00:33 UTC, AntarEspadas commented on backend/src/test/java/io/github/projektalmanac/amoxtli/backend/serviceTest/UserServiceTest.java
> +        Assertions.assertEquals(false,result,"El usuario no esta autenticado");
Lo mismo

2023-10-07 00:04 UTC, laloCastro22 commented
Y

2023-10-07 19:32 UTC, AntarEspadas requested changes

2023-10-07 19:32 UTC, AntarEspadas commented on backend/src/main/java/io/github/projektalmanac/amoxtli/backend/controller/UserController.java
> +        return ResponseEntity.noContent().build();
Quieres regresar una respuesta exitosa incluso si `actualizarFoto` lanza una excepción?

2023-10-07 19:32 UTC, AntarEspadas commented on backend/src/main/java/io/github/projektalmanac/amoxtli/backend/service/UserService.java
> +        user = this.userRepository.save(user);
¿Por qué hacer todo esto en lugar de guardar directamente userAux?

2023-10-07 19:32 UTC, AntarEspadas commented on backend/src/test/java/io/github/projektalmanac/amoxtli/backend/serviceTest/UserServiceTest.java
> +        //Caso 2. El usuario existe pero su correo
¿Pero su correo qué?

2023-10-08 00:01 UTC, AntarEspadas approved these changes

2023-10-08 02:10 UTC, merged